### ISSUE TITLE
support for keywords in IdP search box

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/aai-discovery#1]
Many IdPs have a specific SAML element to make the searching easier:

```
<mdui:Keywords xml:lang="nl">Wageningen Universiteit WUR UR</mdui:Keywords>
```

Would be nice if people could use this when searching for their IdP. In addition, if the organisation name contains diacritics and the organisation does not have a keyword it would make sense to create one ourselve by stripping the diacritics (eg Umeå becomes umea)

**Comment by sanmai-NL** [comment]
Not that the example is wrong, it should have contained: 
```xml
<mdui:Keywords xml:lang="nl">Wageningen+Universiteit WUR UR</mdui:Keywords>
```

**Comment by dietervu** [comment]
Unfortunately indeed the keywoards are not always that useful or even syntactically correct. But we'll have to analyse them and see how we can integrate them into the search functionality.

**Comment by WillemElbers** [comment]
Useful javascript libraries:
https://github.com/mplatt/fold-to-ascii
https://github.com/andrewrk/node-diacritics/blob/master/index.js

**Comment by WillemElbers** [comment]
Replaced by new frontend written in react
