### ISSUE TITLE
sorting by IdP name

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/aai-discovery#4]
Right now, the sorting of the entities (when no geolocalisation is used) is not transparent. I would think alphabetic order by the organisation name (as displayed) makes more sense.

**Comment by WillemElbers** [comment]
First beta release (ui only, not integrated with SAML workflow) available at:
http://dev-idp.clarin.eu/discovery-service-1.8.2/discojuice

Please note this release is also dockerized

**Comment by WillemElbers** [comment]
Fixed by sorting the list of IDPs alphabetically before rendering.
