### ISSUE TITLE
Improve title text

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/aai-discovery#6]
Current text: Sign in to Clarin EU Service Provider
Improved version: Sign in to CLARIN Services

**Comment by sanmai-NL** [comment]
Now that we're focusing on it, another suggested minor improvement over that: ‘Sign in _for_ CLARIN *s*ervices’ (vs. ‘Sign in _to_ an Identity Provider’).

**Comment by sanmai-NL** [comment]
Maybe we should even put: ‘Sign in for protected CLARIN services and resources’. In case some users assume they will first have to go to the central Discovery Service to use any CLARIN services or resource (never overestimate ...), and fail to use it. Will now file another issue for a related possible improvement to the central DS.

**Comment by eiamjw** [comment]
A comment or two from a native speaker of English:

"for" is better than "to", as suggested, as in "Sign in to the CLARIN EU Service Provider"
"the" is necessary there, by the way.

Perhaps it would be best to have both a precise, technically accurate statement of the operation, and a more explanatory text for less technical users. For example:

"Sign in via the CLARIN Service Provider Federation.

Select your identity provider below. This is usually the institution where you work or study. Signing in here will allow you to access certain CLARIN resources and services which are only available to users who have logged in.

If you cannot find your institution in the list above please select the 'Clarin.eu website account' and use your credentials of the CLARIN website. For questions please contact spf@clarin.eu."

Martin

**Comment by dietervu** [comment]
Summarizing the input for #2 and #6, and combining them:

Sign in to Clarin EU Service Provider -> "Sign in via the CLARIN Service Provider Federation."

Select your Identity Provider -> Select your identity provider below. This is usually the institution where you work or study. Signing in here will allow you to access certain CLARIN resources and services which are only available to users who have logged in.

If you cannot find your institution in the list above please select the "Clarin.eu website account" and use your credentials of the CLARIN website. For questions please contact spf@clarin.eu.

->

If you cannot find your institution in the list below please select the <i>clarin.eu website account</i> and use your credentials of the <a href="https://user.clarin.eu/user">CLARIN website</a>. Such accounts can be requested <a href="https://user.clarin.eu/user/register">here</a>. For questions please contact <a href="mailto:spf@clarin.eu">spf@clarin.eu</a>.

**Comment by WillemElbers** [comment]
Implemented in version 1.8.1 and released already a while ago.
