### ISSUE TITLE
Detect and warn if referrer and/or HTTP request parameters are bad

### ISSUE THREAD

**Issue by sanmai-NL** [clarin-eric/aai-discovery#7]
Something that probably can be completed very quickly, and would help usability, is to detect the case where a user tries to visit the central DS directly, by going to https://discovery.clarin.eu/discojuice. Currently, if you do that and you click an IdP, then nothing happens. I could imagine this to be annoying to people who misunderstand the workflow, and perhaps they go on to assume something is technically unavailable because of the lack of feedback.

**Solution**: show warning message when the required parameters are omitted or perhaps also if the referrer suggests a problem.

**Comment by WillemElbers** [comment]
Implemented in version 1.8.1 and released already a while ago.
