### ISSUE TITLE
Danish IdPs listed under Sweden

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/aai-discovery#8]
Since recently, individual SAML entities are made availabe for the Danish IdPs (before all of them had to be accessed via the WAYF.dk hub IdP). Now all Danish entries (eg. University of Copenhagen) appear under the country Sweden.

Note from Sander: we currently get these individual entities via the [Kalmar feed](https://www.kalmar2.org/kalmar2web/tech_info.html)

**Comment by WillemElbers** [comment]
Obviously geoip lookup has it's issues. Especially when the IDP is using a server in a different country. The current proposal is the set country codes based on tld first (if possible) and geolocation second.

**Comment by WillemElbers** [comment]
Fixed by switching to a ccTLD based approach before using the geoip lookup based approach.
