### ISSUE TITLE
University of Applied Sciences BFI Vienna incorrectly displayed as USA

### ISSUE THREAD

**Issue by WillemElbers** [clarin-eric/aai-discovery#9]
The University of Applied Sciences BFI Vienna IDP is incorrectly displayed as a USA based idp.

entityId=https%3A//shibboleth.fh-vie.ac.at/idp/shibboleth

**Comment by dietervu** [comment]
Technically it is correct, as it seems to be hosted at shibboleth-fhbfiwien.cloudapp.net  (microsoft azure). Same goes for the VWA-Hochschule, which is physically hosted in France.

But I agree that we should probably use the TLD (in case of European TLDs) as first criterion to assign countries, and then the geo-lookup.

**Comment by WillemElbers** [comment]
Fixed by switching to a ccTLD based approach before using the geoip lookup based approach.
